site: DevBlog # find a more compelling name
title: DevBlog
greetings: Ciao! 👋
description: >-
  My personal blog! Here I write about a bunch of stuff, mostly related to
  programming and computer science. I hope you enjoy it!
lang: en-US
timezone: Europe/Rome
repo: https://github.com/dario-loi/dario-loi.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: neervana # replace with your disqus shortname
comments-enabled: true # true to enable disqus comments, false to hide them

author:
  name: DevBlog
  bio: CSE student @ Sapienza University of Rome
  userpicture:
  username: neervana # general username
  github: dario-loi # github username
  twitter: # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: dario-loi-5182531b1 # linkedin profile
  email: loi.1940849@studenti.uniroma1.it
# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge # set gruv

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - _examples

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll_picture_tag
  - jekyll-toc

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
